language: ruby
rvm:
  - 2.1.0
env:
  - DB=sqlite
  - DB=postgresql
before_install: cp config/database.travis.yml config/database.yml
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare
before_script:
  - psql -c 'create database strano_test' -U postgres
