require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BooksController do
  include Devise::TestHelpers

  let(:customer) { FactoryGirl.create :admin_customer }
  
  # This should return the minimal set of attributes required to create a valid
  # Book. As you add validations to Book, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { title: Faker::Name.title, description: Faker::Lorem.sentence,
                           price: "9.99", in_stock: "24" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BooksController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  
  let(:ability) { Object.new.extend(CanCan::Ability) }

  before do
    sign_in customer
  end

  describe "GET index" do
    it "assigns all books as @books" do
      book = Book.create! valid_attributes
      get :index, {}, valid_session
      assigns(:books).should eq([book])
    end

    it 'redirect to root if havent read ability' do
      allow(@controller).to receive(:current_ability).and_return(ability)
      ability.cannot :read, Book
      get :index
      response.should redirect_to(root_url)
    end
  end

  describe "GET home" do
    let(:book) { mock_model(Book, id: 1, title: 'name') }

    it "assigns Book.top as @books" do
      expect(Book).to receive(:top).and_return([book])
      get :home, {}, valid_session
      assigns(:books).should eq([book])
    end

    it 'redirect to root if havent home ability' do
      allow(@controller).to receive(:current_ability).and_return(ability)
      ability.cannot :home, Book
      get :home
      response.should redirect_to(root_url)
    end
  end

  describe "GET show" do
    let!(:book) {  Book.create! valid_attributes }
    
    it "assigns the requested book as @book" do
      get :show, {:id => book.to_param}, valid_session
      assigns(:book).should eq(book)
    end

    it "decorate assigned @book" do
      get :show, {:id => book.to_param}, valid_session
      assigns(:book).should be_decorated
    end
    
    it "assigns last 10 approved ratings as @book_ratings" do
      rating = book.ratings.create!(text: "good book", rating: "3", state: 'approved')
      get :show, {:id => book.to_param}, valid_session
      assigns(:book_ratings).should eq([rating])
    end

    it 'redirect to root if havent read ability' do
      allow(@controller).to receive(:current_ability).and_return(ability)
      ability.cannot :read, Book
      allow_any_instance_of(CanCan::ControllerResource).to receive(:load_resource)
      get :show, { id: '1'}
      response.should redirect_to(root_url)
    end
  end
  
  describe "POST rate" do
    let(:book) { Book.create! valid_attributes }

    before do
      request.env["HTTP_REFERER"] = books_path
    end

    it 'redirect to root if havent rate ability' do
      allow(@controller).to receive(:current_ability).and_return(ability)
      ability.cannot :rate, Book
      allow_any_instance_of(CanCan::ControllerResource).to receive(:load_resource)
      post :rate, { id: '1' }
      response.should redirect_to(root_url)
    end
    
    describe "valid attributes" do
      it "adds new rating" do
        expect {
          post :rate, {:id => book.to_param, text: "text rating", rating: "4"}, valid_session
        }.to change(book.ratings, :count).by(1)
      end
      
      it "adds successed flash message" do
        post :rate, {:id => book.to_param, text: "text rating", rating: "4"}, valid_session
        expect(flash[:info]).to eq(I18n.t 'suc_rating_add')
      end
      
      it "redirects back" do
        post :rate, {:id => book.to_param, text: "text rating", rating: "4"}, valid_session
         response.should redirect_to(books_path)
      end
    end
    
    describe "invalid attributes" do
      it "adds error flash message" do
        post :rate, {:id => book.to_param, text: "text rating", rating: "8"}, valid_session
        expect(flash[:info]).to_not eq(I18n.t 'suc_rating_add')
        expect(flash[:danger]).to_not be_empty
      end
      
      it "redirects back" do
       post :rate, {:id => book.to_param, text: "text rating", rating: "8"}, valid_session
       response.should redirect_to(books_path)
      end
    end
  end
  
  describe "DELETE wished" do
    let(:book) { Book.create! valid_attributes }

    it 'redirect to root if havent wished ability' do
      allow(@controller).to receive(:current_ability).and_return(ability)
      ability.cannot :wished, Book
      allow_any_instance_of(CanCan::ControllerResource).to receive(:load_resource)
      delete :wished, { id: '1' }
      response.should redirect_to(root_url)
    end

    it "delete book from wished list" do
      book.wish_add(customer)
      expect {
        delete :wished, {:id => book.to_param}, valid_session
      }.to change(book.wished_customers, :count).by(-1)
    end

    it "redirects to customer profile" do
      delete :wished, {:id => book.to_param}, valid_session
      response.should redirect_to(customer)
    end
  end
  
  describe "POST add_wished" do
    let(:book) { Book.create! valid_attributes }
    before do
      allow_any_instance_of(Book).to receive(:wish_add)
    end

    it 'redirect to root if havent add_wished ability' do
      allow(@controller).to receive(:current_ability).and_return(ability)
      ability.cannot :add_wished, Book
      allow_any_instance_of(CanCan::ControllerResource).to receive(:load_resource)
      post :add_wished, { id: '1' }
      response.should redirect_to(root_url)
    end
    
    it "calls wish_add" do
      expect_any_instance_of(Book).to receive(:wish_add)
      post :add_wished, {:id => book.to_param}, valid_session
    end
    
    it "redirects to show book path" do
      post :add_wished, {:id => book.to_param}, valid_session
      response.should redirect_to(book_path(book))
    end
      
    describe "all valid" do
      it "adds success flash message" do
        allow_any_instance_of(Book).to receive(:wish_add).and_return(true)
        post :add_wished, {:id => book.to_param}, valid_session
        expect(flash[:info]).to eq I18n.t 'suc_wish_add'
      end
    end
    
    describe "already rated" do
      it "adds error flash message" do
        allow_any_instance_of(Book).to receive(:wish_add).and_return(false)
        post :add_wished, {:id => book.to_param}, valid_session
        expect(flash[:info]).to_not eq I18n.t 'suc_wish_add'
        expect(flash[:danger]).to eq I18n.t 'err_wish_add'
      end
    end   
  end  
  
  describe "GET filter" do
    let(:book) { Book.create! valid_attributes }
    
    it 'redirect to root if havent filter ability' do
      allow(@controller).to receive(:current_ability).and_return(ability)
      ability.cannot :filter, Book
      get :filter, { id: '1' }
      response.should redirect_to(root_url)
    end

    it "redirects to books path if reset button was clicked" do
      get :filter, {:id => book.to_param, :commit => I18n.t('reset')}, valid_session
      expect(response).to redirect_to(books_path)
    end
    
    before do
      Book.stub_chain("filter.includes").and_return([book])
      allow_any_instance_of(Array).to receive('page').and_return([book])
      allow_any_instance_of(Array).to receive('per').and_return([book])
    end
    
    it "filtering books by parameters" do
      expect(Book).to receive(:filter)
      expect(Book.filter).to receive(:includes)
      get :filter, {:id => book.to_param, :authors_id => [""], :categories_id => [""], :books_id => [book.id]}, valid_session
      expect(assigns(:books)).to eq([book])
    end
    
    it "renders index template" do
      get :filter, {:id => book.to_param, :authors_id => [""], :categories_id => [""], :books_id => [book.id]}, valid_session
      expect(response).to render_template("index")
    end
  end
  
end
